### ISSUE TITLE
Lv.1 코드 리뷰

### ISSUE THREAD

**Issue by dragonrain5761** [miinxxi/hh99_todolist#1]
👍 코드가 정말 좋네요! App.js에 있는 컴포넌트를 분리 시키시면 가독성과 재사용성이 올라갈 것 같아요!

 👍 코드가 정말 깔끔하네요! 제목과 내용을 div로 한번 더 감싸주시면, 글자수가 너무 많을 경우 상자밖으로 나가는 에러를 막을 수 있을 것 같아요!

**Comment by miinxxi** [comment]
좋게 봐주셔서 감사합니다! 안그래도 리팩토링해봐야겠다고 생각했어서 참고해서 만들어보겠습니다~ 감사합니다!

**Comment by miinxxi** [comment]
> 

좋게 봐주셔서 감사합니다! 안그래도 리팩토링을 해봐야겠다고 생각했어서 참고해서 만들어보겠습니다~ 감사합니다!
